service: notes-api

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource: arn:aws:dynamodb:eu-north-1:816069166797:table/NotesTable

functions:
  # Auth functions
  signup:
    handler: auth.signup
    events:
      - http:
          path: user/signup
          method: post
          cors: true

  login:
    handler: auth.login
    events:
      - http:
          path: user/login
          method: post
          cors: true

  # Notes functions
  getNotes:
    handler: handler.getNotes  # Kopplar till handler.js och funktionen getNotes
    events:
      - http:
          path: notes
          method: get
          cors: true

  addNote:
    handler: handler.addNote  # Kopplar till handler.js och funktionen addNote
    events:
      - http:
          path: notes
          method: post
          cors: true

  updateNote:
    handler: handler.updateNote  # Kopplar till handler.js och funktionen updateNote
    events:
      - http:
          path: notes
          method: put
          cors: true

  deleteNote:
    handler: handler.deleteNote  # Kopplar till handler.js och funktionen deleteNote
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true


resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: NotesTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5